### ISSUE TITLE
VERSION undefined

### ISSUE THREAD

**Issue by pamolloy** [robm/dzen#1]
This is really an almost insignificant issue, but I thought I would note that the replacement text, `VERSION`, within the control flow for the version (i.e. `-v`) option, is not defined.

**Comment by emberian** [comment]
How did you determine that? It is defined: it is passed in as a macro from the makefile. See line 2 and 43 of config.mk

**Comment by pamolloy** [comment]
Thanks for pointing that out. For some reason the dzen2 package currently in the Arch Linux community repository isn't returning that value.

``` bash
$ pacman -Ss dzen2
community/dzen2 0.8.5-7 [installed]
    X notification utility
$ dzen2 -v
dzen-, (C)opyright 2007 Robert Manea
```

I used the PKGBUILD from the aforementioned package to build the current source code hosted here and it works just fine.
