### ISSUE TITLE
Menu mode command line parsing

### ISSUE THREAD

**Issue by pamolloy** [robm/dzen#2]
I was looking at the menu option (i.e. `-m`) control flow since it's the only option with an optional argument and noticed it doesn't process the option correctly when given a `v` argument.

For example, the following example from the Examples section in the README returns the usage information rather than creating a vertical mode (using version 0.8.5-7):

``` bash
dzen2 -p -l 4 -m v < file
```

**Comment by emberian** [comment]
Works For Me.

**Comment by pamolloy** [comment]
As with the other issue I opened I can not reproduce this bug with the current source code.
