### ISSUE TITLE
Title Bar does weird things with wildcards

### ISSUE THREAD

**Issue by theVDude** [robm/dzen#3]
if you load up a browser with this page http://pastebin.com/47jj8C1n you'll get a listing of your home directory in the dzen title bar: http://i.imgur.com/5ElKK.png

:/ I'm pretty sure it shouldn't work like that. Maybe it's something I've done wrong?

**Comment by pamolloy** [comment]
How do you have dzen configured to display the current window name?

**Comment by theVDude** [comment]
It was an issue with herbstluftwm's default implementation, I added set -f to the beginning of my panel.sh and that fixed it. :/
