### ISSUE TITLE
dzen2 disappearing seconds after booting and pressing keys

### ISSUE THREAD

**Issue by Popkultur** [robm/dzen#44]
Hi,

This is my xmonad.hs whch calls dzen2 two times: https://pastebin.com/BDdbT0ZY
The right Bar works, the left Bar disappears after some seconds after login and if pressing keys for window layouts in xmonad. With the -p -e parameters, it does not vanish but does not show any content after all. I have no clue where the problem might be. OS is OpenBSD, xmonad 0.11.1, dzen2 0.9.5

**Comment by poinck** [comment]
I know this behaviour when child-window has too many rows to be displayed on the screen. But, I am not familiar with Xmonad and what it is doing with dzen2.

**Comment by Popkultur** [comment]
I presume it was a faulty xmonad.hs so it works now with a different bar but it might work now with dzen2 too
